languaje: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
install: composer install --dev
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script: phpunit tests/
matrix:
  fast_finish: true
sudo: required
notifications:
  on_success: never
  on_failure: always