language: php
php:
  - '5.6'
matrix:
  fast_finish: true
sudo: required
before_install:
  - sudo apt-get update > /dev/null
script:
  composer install
  phpunit /tests/
branches:
  only:
    - master
